### ISSUE TITLE
Despicate of basins_of_attractor

### ISSUE THREAD

**Issue by Mmarwan92** [awage/Basins.jl#1]
Greetings respected writer of Basins.jl

Thanks for uploading your codes to Github. But, unfortunatly, none of your example is running. 

Kindly, please try to run one of your example like for lorenz84. In each code 
basins_map2D()
Is not working and is giving error as 
Basin2D is Despicate of basins_of_attractor

**Comment by awage** [comment]
Hello, this repository is intended for experimental features. Use ChaosTools.jl to compute basins.  The algorithm has been tested and documented thoroughly. 

I have also have contributed to ChaosTools.jl actively and I have received the issue you have opened there. 

Best
